const aiFormConfigs = {
  'staging-suggestions': {
    desc: 'Get AI-powered room staging suggestions tailored to your property.',
    fields: [
      { name: 'roomType', label: 'Room Type', type: 'select', options: ['Living Room', 'Bedroom', 'Kitchen', 'Dining Room', 'Bathroom', 'Home Office', 'Entryway', 'Outdoor Patio'] },
      { name: 'roomSize', label: 'Room Size (sq ft)', type: 'number', placeholder: '300' },
      { name: 'currentCondition', label: 'Current Condition', type: 'select', options: ['Excellent', 'Good', 'Fair', 'Poor', 'Empty'] },
      { name: 'style', label: 'Style', type: 'select', options: ['Modern', 'Contemporary', 'Farmhouse', 'Coastal', 'Industrial', 'Scandinavian', 'Traditional', 'Mid-Century Modern', 'Bohemian', 'Transitional', 'Luxury'] },
      { name: 'budget', label: 'Budget ($)', type: 'number', placeholder: '5000' },
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Loft', 'Cabin', 'Studio'] },
    ],
  },
  'color-palette': {
    desc: 'Generate professional color palettes with psychology-backed recommendations.',
    fields: [
      { name: 'roomType', label: 'Room Type', type: 'select', options: ['Living Room', 'Bedroom', 'Kitchen', 'Dining Room', 'Bathroom', 'Home Office', 'Nursery', 'Entryway'] },
      { name: 'style', label: 'Style', type: 'select', options: ['Contemporary', 'Farmhouse', 'Coastal', 'Industrial', 'Scandinavian', 'Traditional', 'Art Deco', 'Bohemian', 'Mediterranean', 'Japanese Zen'] },
      { name: 'mood', label: 'Mood', type: 'select', options: ['Warm and inviting', 'Cool and serene', 'Bold and dramatic', 'Light and airy', 'Cozy and intimate', 'Energetic and vibrant', 'Elegant and luxurious'] },
      { name: 'existingColors', label: 'Existing Colors', type: 'text', placeholder: 'e.g., White cabinets, dark hardwood floors' },
      { name: 'naturalLight', label: 'Natural Light', type: 'select', options: ['Abundant', 'Moderate', 'Limited', 'North-facing', 'South-facing'] },
    ],
  },
  'listing-generator': {
    desc: 'Create compelling property listing descriptions that sell.',
    fields: [
      { name: 'propertyTitle', label: 'Property Title', type: 'text', placeholder: 'Beautiful Modern Home' },
      { name: 'address', label: 'Address', type: 'text', placeholder: '123 Main St, San Francisco' },
      { name: 'bedrooms', label: 'Bedrooms', type: 'number', placeholder: '3' },
      { name: 'bathrooms', label: 'Bathrooms', type: 'number', placeholder: '2' },
      { name: 'sqft', label: 'Square Feet', type: 'number', placeholder: '2000' },
      { name: 'price', label: 'Price ($)', type: 'number', placeholder: '750000' },
      { name: 'features', label: 'Features', type: 'textarea', placeholder: 'Modern kitchen, hardwood floors, large backyard, mountain views' },
      { name: 'style', label: 'Style', type: 'text', placeholder: 'Contemporary' },
      { name: 'targetAudience', label: 'Target Audience', type: 'text', placeholder: 'Young professionals and families' },
    ],
  },
  'budget-estimator': {
    desc: 'Get detailed staging budget estimates with ROI projections.',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Loft', 'Cabin', 'Luxury Estate'] },
      { name: 'sqft', label: 'Square Feet', type: 'number', placeholder: '2000' },
      { name: 'rooms', label: 'Number of Rooms', type: 'number', placeholder: '5' },
      { name: 'style', label: 'Style', type: 'select', options: ['Transitional', 'Contemporary', 'Luxury', 'Farmhouse', 'Coastal', 'Minimalist', 'Traditional'] },
      { name: 'market', label: 'Market', type: 'select', options: ['Urban Luxury', 'Urban Standard', 'Suburban', 'Rural', 'Resort/Vacation'] },
      { name: 'timeline', label: 'Timeline', type: 'select', options: ['1 week', '2 weeks', '3 weeks', '1 month', 'Rush (3 days)'] },
    ],
  },
  'style-recommender': {
    desc: 'AI recommends the perfect design style for your property and market.',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Loft', 'Cabin', 'Historic Home'] },
      { name: 'architecture', label: 'Architecture', type: 'select', options: ['Modern', 'Victorian', 'Colonial', 'Craftsman', 'Ranch', 'Mediterranean', 'Mid-Century', 'Contemporary', 'Industrial'] },
      { name: 'neighborhood', label: 'Neighborhood', type: 'select', options: ['Urban professional', 'Suburban family', 'Trendy/hip', 'Historic district', 'Beach community', 'Mountain town', 'Luxury enclave'] },
      { name: 'targetBuyer', label: 'Target Buyer', type: 'select', options: ['Young professionals', 'Growing families', 'Empty nesters', 'Luxury buyers', 'First-time buyers', 'Investors', 'Retirees'] },
      { name: 'priceRange', label: 'Price Range', type: 'select', options: ['Under $300k', '$300k-$500k', '$500k-$800k', '$800k-$1.2M', '$1.2M-$2M', '$2M+'] },
      { name: 'existingFeatures', label: 'Existing Features', type: 'textarea', placeholder: 'Open floor plan, large windows, fireplace, hardwood floors' },
    ],
  },
  'furniture-placement': {
    desc: 'Get optimal furniture layout suggestions for maximum buyer appeal.',
    fields: [
      { name: 'roomType', label: 'Room Type', type: 'select', options: ['Living Room', 'Bedroom', 'Dining Room', 'Home Office', 'Family Room', 'Great Room'] },
      { name: 'dimensions', label: 'Dimensions', type: 'text', placeholder: '15ft x 20ft' },
      { name: 'features', label: 'Features', type: 'textarea', placeholder: 'Large window on south wall, fireplace on east wall, open to kitchen' },
      { name: 'style', label: 'Style', type: 'select', options: ['Contemporary', 'Traditional', 'Transitional', 'Mid-Century', 'Farmhouse', 'Coastal'] },
      { name: 'furnitureList', label: 'Furniture List', type: 'textarea', placeholder: 'Sofa, coffee table, two accent chairs, console table, area rug' },
    ],
  },
  'before-after': {
    desc: 'Generate compelling transformation narratives for marketing.',
    fields: [
      { name: 'roomName', label: 'Room Name', type: 'text', placeholder: 'Master Living Room' },
      { name: 'beforeState', label: 'Before State', type: 'textarea', placeholder: 'Empty, dated room with worn carpet and bare walls' },
      { name: 'afterStyle', label: 'After Style', type: 'select', options: ['Modern', 'Farmhouse', 'Coastal', 'Industrial', 'Luxury', 'Transitional', 'Scandinavian'] },
      { name: 'changesApplied', label: 'Changes Applied', type: 'textarea', placeholder: 'New paint, furniture staging, accessories, updated lighting' },
      { name: 'budget', label: 'Budget ($)', type: 'number', placeholder: '5000' },
    ],
  },
  'market-analysis': {
    desc: 'AI-powered market analysis with staging ROI predictions.',
    fields: [
      { name: 'region', label: 'Region', type: 'text', placeholder: 'San Francisco Bay Area' },
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Luxury', 'Multi-family'] },
      { name: 'priceRange', label: 'Price Range', type: 'select', options: ['Under $300k', '$300k-$500k', '$500k-$800k', '$800k-$1.2M', '$1.2M-$2M', '$2M+'] },
      { name: 'targetSeason', label: 'Target Season', type: 'select', options: ['Spring 2024', 'Summer 2024', 'Fall 2024', 'Winter 2024', 'Year-round'] },
    ],
  },
  'checklist-generator': {
    desc: 'Auto-generate comprehensive day-by-day staging checklists.',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Loft'] },
      { name: 'rooms', label: 'Rooms', type: 'textarea', placeholder: 'Living room, kitchen, master bedroom, bathroom, dining room' },
      { name: 'style', label: 'Style', type: 'select', options: ['Contemporary', 'Transitional', 'Farmhouse', 'Luxury', 'Coastal', 'Minimalist'] },
      { name: 'timeline', label: 'Timeline', type: 'select', options: ['5 days', '7 days', '10 days', '14 days', '21 days'] },
      { name: 'budget', label: 'Budget ($)', type: 'number', placeholder: '8000' },
    ],
  },
  'virtual-staging': {
    desc: 'Get detailed virtual staging plans and tool recommendations.',
    fields: [
      { name: 'roomType', label: 'Room Type', type: 'select', options: ['Living Room', 'Bedroom', 'Kitchen', 'Dining Room', 'Bathroom', 'Home Office'] },
      { name: 'currentState', label: 'Current State', type: 'textarea', placeholder: 'Empty room with white walls and hardwood floors' },
      { name: 'desiredStyle', label: 'Desired Style', type: 'select', options: ['Modern Luxury', 'Scandinavian', 'Farmhouse', 'Coastal', 'Industrial', 'Mid-Century', 'Traditional', 'Contemporary'] },
      { name: 'budget', label: 'Budget ($)', type: 'number', placeholder: '200' },
    ],
  },
  'property-analyzer': {
    desc: 'Comprehensive AI property analysis with staging strategy and buyer targeting.',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Loft', 'Cabin', 'Luxury Estate'] },
      { name: 'location', label: 'Location', type: 'text', placeholder: 'Suburban neighborhood, San Francisco' },
      { name: 'sqft', label: 'Square Feet', type: 'number', placeholder: '2000' },
      { name: 'bedrooms', label: 'Bedrooms', type: 'number', placeholder: '3' },
      { name: 'bathrooms', label: 'Bathrooms', type: 'number', placeholder: '2' },
      { name: 'age', label: 'Age', type: 'text', placeholder: '10 years' },
      { name: 'condition', label: 'Condition', type: 'select', options: ['Excellent', 'Good', 'Fair', 'Poor', 'Needs renovation'] },
      { name: 'price', label: 'Price ($)', type: 'number', placeholder: '500000' },
    ],
  },
  'room-optimizer': {
    desc: 'AI spatial design optimization to make any room feel larger and more appealing.',
    fields: [
      { name: 'roomType', label: 'Room Type', type: 'select', options: ['Living Room', 'Bedroom', 'Kitchen', 'Dining Room', 'Bathroom', 'Home Office', 'Nursery', 'Basement', 'Attic'] },
      { name: 'width', label: 'Width (ft)', type: 'number', placeholder: '14' },
      { name: 'length', label: 'Length (ft)', type: 'number', placeholder: '18' },
      { name: 'ceilingHeight', label: 'Ceiling Height', type: 'select', options: ['8 ft (standard)', '9 ft', '10 ft', '12+ ft (vaulted)', 'Sloped/attic'] },
      { name: 'issues', label: 'Issues', type: 'textarea', placeholder: 'Feels small, poor lighting, awkward layout, dark corners' },
      { name: 'purpose', label: 'Purpose', type: 'text', placeholder: 'Show as versatile living space' },
    ],
  },
  'client-proposal': {
    desc: 'Generate professional staging proposals to win clients.',
    fields: [
      { name: 'clientName', label: 'Client Name', type: 'text', placeholder: 'Jane Smith' },
      { name: 'clientType', label: 'Client Type', type: 'select', options: ['Real Estate Agent', 'Homeowner', 'Investor', 'Developer', 'Property Manager'] },
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Luxury Estate', 'Multi-unit'] },
      { name: 'propertyAddress', label: 'Property Address', type: 'text', placeholder: '123 Main St, San Francisco' },
      { name: 'budget', label: 'Budget ($)', type: 'text', placeholder: '5000-10000' },
      { name: 'timeline', label: 'Timeline', type: 'select', options: ['1 week', '2 weeks', '3 weeks', '1 month', 'Flexible'] },
      { name: 'goals', label: 'Goals', type: 'textarea', placeholder: 'Sell faster, maximize sale price, attract specific buyer type' },
    ],
  },
  'appointment-planner': {
    desc: 'AI-powered consultation planning for maximum effectiveness.',
    fields: [
      { name: 'appointmentType', label: 'Appointment Type', type: 'select', options: ['Initial Consultation', 'Design Walkthrough', 'Staging Day', 'Photography Prep', 'De-staging', 'Client Presentation', 'Open House Prep'] },
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Loft', 'Luxury Estate'] },
      { name: 'propertySize', label: 'Property Size', type: 'text', placeholder: '2000 sqft' },
      { name: 'clientType', label: 'Client Type', type: 'select', options: ['Real Estate Agent', 'Homeowner', 'Investor', 'Developer'] },
      { name: 'duration', label: 'Duration', type: 'select', options: ['30 minutes', '60 minutes', '90 minutes', '2 hours', '3+ hours'] },
      { name: 'goals', label: 'Goals', type: 'textarea', placeholder: 'Assess property and present staging plan' },
    ],
  },
  'pricing-calculator': {
    desc: 'AI pricing strategy and invoice generation for staging projects.',
    fields: [
      { name: 'serviceType', label: 'Service Type', type: 'select', options: ['Full Home Staging', 'Partial Staging', 'Consultation Only', 'Virtual Staging', 'Occupied Staging', 'Luxury Staging', 'Model Home'] },
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Luxury Estate'] },
      { name: 'sqft', label: 'Square Feet', type: 'number', placeholder: '2000' },
      { name: 'rooms', label: 'Number of Rooms', type: 'number', placeholder: '5' },
      { name: 'market', label: 'Market', type: 'select', options: ['Urban Luxury', 'Urban Standard', 'Suburban High-end', 'Suburban Standard', 'Rural'] },
      { name: 'duration', label: 'Duration', type: 'select', options: ['30 days', '60 days', '90 days', '6 months'] },
      { name: 'extras', label: 'Extras', type: 'textarea', placeholder: 'Photography, consultation, de-staging, holiday refresh' },
    ],
  },
  'furniture-recommender': {
    desc: 'AI furniture selection and sourcing recommendations for any room.',
    fields: [
      { name: 'roomType', label: 'Room Type', type: 'select', options: ['Living Room', 'Bedroom', 'Kitchen', 'Dining Room', 'Bathroom', 'Home Office', 'Outdoor'] },
      { name: 'style', label: 'Style', type: 'select', options: ['Contemporary', 'Farmhouse', 'Coastal', 'Industrial', 'Scandinavian', 'Mid-Century', 'Traditional', 'Bohemian', 'Luxury'] },
      { name: 'budget', label: 'Budget ($)', type: 'number', placeholder: '3000' },
      { name: 'roomSize', label: 'Room Size', type: 'text', placeholder: '15x20 ft' },
      { name: 'existingPieces', label: 'Existing Pieces', type: 'textarea', placeholder: 'None, or list existing furniture to work with' },
      { name: 'colorScheme', label: 'Color Scheme', type: 'text', placeholder: 'Neutral warm tones' },
    ],
  },
  'vendor-matcher': {
    desc: 'AI vendor selection and coordination strategy for staging projects.',
    fields: [
      { name: 'serviceNeeded', label: 'Service Needed', type: 'select', options: ['Furniture Rental', 'Photography', 'Cleaning', 'Painting', 'Floral', 'Moving/Logistics', 'Art Rental', 'Landscaping', 'Full Staging Package'] },
      { name: 'location', label: 'Location', type: 'text', placeholder: 'San Francisco Bay Area' },
      { name: 'budget', label: 'Budget ($)', type: 'number', placeholder: '5000' },
      { name: 'timeline', label: 'Timeline', type: 'select', options: ['Rush (3 days)', '1 week', '2 weeks', '1 month', 'Flexible'] },
      { name: 'quality', label: 'Quality', type: 'select', options: ['Budget-friendly', 'Mid-range', 'High-end', 'Ultra-luxury'] },
      { name: 'projectType', label: 'Project Type', type: 'select', options: ['Residential staging', 'Luxury home staging', 'Model home', 'Commercial staging', 'Vacation rental'] },
    ],
  },
  'roi-calculator': {
    desc: 'Calculate the precise financial return on staging investments.',
    fields: [
      { name: 'listingPrice', label: 'Listing Price ($)', type: 'number', placeholder: '500000' },
      { name: 'stagingCost', label: 'Staging Cost ($)', type: 'number', placeholder: '8000' },
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Luxury Estate'] },
      { name: 'market', label: 'Market', type: 'select', options: ['Hot sellers market', 'Balanced market', 'Buyers market', 'Luxury market', 'Competitive suburban'] },
      { name: 'daysOnMarket', label: 'Days on Market', type: 'number', placeholder: '0' },
      { name: 'condition', label: 'Condition', type: 'select', options: ['Excellent', 'Good', 'Fair', 'Needs work'] },
    ],
  },
  'curb-appeal': {
    desc: 'AI exterior and curb appeal staging for stunning first impressions.',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Townhouse', 'Condo (entrance)', 'Luxury Estate', 'Cabin'] },
      { name: 'exteriorCondition', label: 'Exterior Condition', type: 'select', options: ['Excellent', 'Good', 'Average', 'Needs attention', 'Major work needed'] },
      { name: 'landscaping', label: 'Landscaping', type: 'textarea', placeholder: 'Basic lawn, few shrubs, no flowers' },
      { name: 'budget', label: 'Budget ($)', type: 'number', placeholder: '2000' },
      { name: 'season', label: 'Season', type: 'select', options: ['Spring', 'Summer', 'Fall', 'Winter'] },
      { name: 'issues', label: 'Issues', type: 'textarea', placeholder: 'Dated front door, faded paint, bare flower beds' },
    ],
  },
  'lighting-design': {
    desc: 'Professional AI lighting plans for every room and mood.',
    fields: [
      { name: 'roomType', label: 'Room Type', type: 'select', options: ['Living Room', 'Bedroom', 'Kitchen', 'Dining Room', 'Bathroom', 'Home Office', 'Hallway', 'Exterior'] },
      { name: 'roomSize', label: 'Room Size', type: 'text', placeholder: '15x20 ft' },
      { name: 'naturalLight', label: 'Natural Light', type: 'select', options: ['Abundant - south facing', 'Moderate', 'Limited - north facing', 'Minimal - basement/interior'] },
      { name: 'currentFixtures', label: 'Current Fixtures', type: 'textarea', placeholder: 'Basic overhead light only, no dimmers' },
      { name: 'style', label: 'Style', type: 'select', options: ['Contemporary', 'Traditional', 'Industrial', 'Farmhouse', 'Luxury', 'Scandinavian'] },
      { name: 'mood', label: 'Mood', type: 'select', options: ['Warm and inviting', 'Bright and energetic', 'Cozy and intimate', 'Dramatic and luxurious', 'Clean and professional'] },
    ],
  },
  'seasonal-staging': {
    desc: 'Season-specific staging strategies for year-round market appeal.',
    fields: [
      { name: 'season', label: 'Season', type: 'select', options: ['Spring', 'Summer', 'Fall', 'Winter', 'Holiday Season (Nov-Dec)'] },
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Cabin', 'Beach House', 'Luxury Estate'] },
      { name: 'style', label: 'Style', type: 'select', options: ['Contemporary', 'Farmhouse', 'Coastal', 'Traditional', 'Transitional'] },
      { name: 'region', label: 'Region', type: 'select', options: ['Northeast US', 'Southeast US', 'Midwest US', 'Southwest US', 'Pacific Northwest', 'California'] },
      { name: 'targetBuyer', label: 'Target Buyer', type: 'select', options: ['Families', 'Young professionals', 'Retirees', 'Luxury buyers', 'First-time buyers'] },
      { name: 'holidays', label: 'Holidays', type: 'text', placeholder: 'e.g., Thanksgiving, Christmas, or none' },
    ],
  },
  'decluttering-guide': {
    desc: 'AI decluttering and pre-staging preparation strategies.',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Studio', 'Luxury Home'] },
      { name: 'rooms', label: 'Rooms', type: 'textarea', placeholder: 'All rooms, or specify: kitchen, master bedroom, garage' },
      { name: 'occupancyStatus', label: 'Occupancy Status', type: 'select', options: ['Currently occupied', 'Recently vacated', 'Tenant occupied', 'Estate/inherited', 'Hoarder situation'] },
      { name: 'clutterLevel', label: 'Clutter Level', type: 'select', options: ['Light - mostly organized', 'Moderate - typical lived-in', 'Heavy - lots of personal items', 'Severe - significant accumulation'] },
      { name: 'timeline', label: 'Timeline', type: 'select', options: ['3 days', '1 week', '2 weeks', '1 month'] },
      { name: 'sensitiveItems', label: 'Sensitive Items', type: 'textarea', placeholder: 'Family with children, elderly owner, pet household' },
    ],
  },
  'photo-staging': {
    desc: 'AI photography preparation and styling for listing photos.',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Luxury Estate'] },
      { name: 'rooms', label: 'Rooms', type: 'textarea', placeholder: 'All staged rooms + exterior, or specify rooms' },
      { name: 'photographer', label: 'Photographer', type: 'select', options: ['Professional real estate photographer', 'Twilight/dusk specialist', 'Drone + interior', 'DIY/agent photography', 'Video walkthrough'] },
      { name: 'platform', label: 'Platform', type: 'text', placeholder: 'MLS, Zillow, Realtor.com, Instagram' },
      { name: 'style', label: 'Style', type: 'select', options: ['Contemporary', 'Farmhouse', 'Luxury', 'Coastal', 'Traditional', 'Industrial'] },
      { name: 'specialFeatures', label: 'Special Features', type: 'textarea', placeholder: 'Pool, fireplace, city views, chef kitchen' },
    ],
  },
  'renovation-advisor': {
    desc: 'AI pre-sale renovation recommendations for maximum ROI.',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Fixer-upper', 'Historic Home'] },
      { name: 'budget', label: 'Budget ($)', type: 'number', placeholder: '10000' },
      { name: 'areas', label: 'Areas', type: 'textarea', placeholder: 'Kitchen, bathrooms, flooring, paint, fixtures' },
      { name: 'age', label: 'Age', type: 'text', placeholder: '20 years' },
      { name: 'goal', label: 'Goal', type: 'select', options: ['Maximize sale price', 'Quick sale', 'Pass inspection', 'Compete with new construction', 'Appeal to luxury buyers'] },
      { name: 'timeline', label: 'Timeline', type: 'select', options: ['1 week', '2 weeks', '1 month', '2 months', '3+ months'] },
    ],
  },
  'valuation-impact': {
    desc: 'AI analysis of how staging impacts property valuation and sale price.',
    fields: [
      { name: 'currentValue', label: 'Current Value ($)', type: 'number', placeholder: '500000' },
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Luxury Estate'] },
      { name: 'stagingPlan', label: 'Staging Plan', type: 'textarea', placeholder: 'Full home staging, 6 rooms, contemporary style' },
      { name: 'market', label: 'Market', type: 'select', options: ['Hot sellers market', 'Balanced market', 'Buyers market', 'Luxury niche', 'New construction competition'] },
      { name: 'comparables', label: 'Comparables', type: 'textarea', placeholder: 'Similar homes selling at $480k-$530k' },
      { name: 'condition', label: 'Condition', type: 'select', options: ['Move-in ready', 'Good but dated', 'Needs updates', 'Fixer-upper'] },
    ],
  },
  'neighborhood-strategy': {
    desc: 'AI neighborhood-specific staging and marketing strategy.',
    fields: [
      { name: 'neighborhood', label: 'Neighborhood', type: 'text', placeholder: 'Pacific Heights, San Francisco' },
      { name: 'demographics', label: 'Demographics', type: 'select', options: ['Young families', 'Professionals/DINK', 'Retirees', 'Students/young adults', 'Affluent mixed', 'Diverse suburban'] },
      { name: 'priceRange', label: 'Price Range', type: 'select', options: ['Under $300k', '$300k-$500k', '$500k-$800k', '$800k-$1.2M', '$1.2M-$2M', '$2M+'] },
      { name: 'competition', label: 'Competition', type: 'text', placeholder: '15 active listings in area' },
      { name: 'trends', label: 'Trends', type: 'textarea', placeholder: 'Steady growth, 5% YoY appreciation, tech buyers moving in' },
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Multi-unit'] },
    ],
  },
  'project-planner': {
    desc: 'Complete AI project management plan for staging projects.',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Luxury Estate', 'Model Home'] },
      { name: 'rooms', label: 'Rooms', type: 'text', placeholder: '6 rooms' },
      { name: 'budget', label: 'Budget ($)', type: 'number', placeholder: '10000' },
      { name: 'style', label: 'Style', type: 'select', options: ['Transitional', 'Contemporary', 'Farmhouse', 'Luxury', 'Coastal', 'Mid-Century'] },
      { name: 'teamSize', label: 'Team Size', type: 'select', options: ['Solo stager', '2 people', '3-4 people', '5+ people'] },
      { name: 'startDate', label: 'Start Date', type: 'text', placeholder: 'Next Monday' },
      { name: 'showingDate', label: 'Showing Date', type: 'text', placeholder: '2 weeks from start' },
    ],
  },
  'open-house-optimizer': {
    desc: 'AI open house experience design for maximum buyer engagement.',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Luxury Estate'] },
      { name: 'style', label: 'Style', type: 'select', options: ['Contemporary', 'Farmhouse', 'Coastal', 'Luxury', 'Traditional', 'Transitional'] },
      { name: 'expectedVisitors', label: 'Expected Visitors', type: 'select', options: ['Under 10', '10-20', '20-50', '50-100', '100+'] },
      { name: 'duration', label: 'Duration', type: 'text', placeholder: '2 hours (Sunday 1-3 PM)' },
      { name: 'season', label: 'Season', type: 'select', options: ['Spring', 'Summer', 'Fall', 'Winter'] },
      { name: 'targetBuyer', label: 'Target Buyer', type: 'select', options: ['Families', 'Young professionals', 'Luxury buyers', 'First-time buyers', 'Retirees'] },
    ],
  },
  'social-media': {
    desc: 'AI social media content creation for staging marketing.',
    fields: [
      { name: 'platform', label: 'Platform', type: 'select', options: ['Instagram', 'Facebook', 'TikTok', 'Pinterest', 'LinkedIn', 'YouTube', 'All platforms'] },
      { name: 'contentType', label: 'Content Type', type: 'select', options: ['Before/After Showcase', 'Staging Tips', 'Property Highlight', 'Behind the Scenes', 'Client Testimonial', 'Market Update', 'Design Inspiration'] },
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Luxury', 'Unique/Special'] },
      { name: 'style', label: 'Style', type: 'text', placeholder: 'Contemporary' },
      { name: 'targetAudience', label: 'Target Audience', type: 'select', options: ['Real estate agents', 'Homeowners selling', 'Interior design enthusiasts', 'Home buyers', 'Industry professionals'] },
      { name: 'brandVoice', label: 'Brand Voice', type: 'select', options: ['Professional yet approachable', 'Luxury and exclusive', 'Fun and trendy', 'Educational and expert', 'Warm and personal'] },
    ],
  },
  'trend-forecaster': {
    desc: 'AI staging and design trend predictions to stay ahead of the market.',
    fields: [
      { name: 'region', label: 'Region', type: 'select', options: ['National (US)', 'Northeast', 'Southeast', 'Midwest', 'Southwest', 'West Coast', 'Pacific Northwest'] },
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['All residential', 'Single Family', 'Condos/Urban', 'Luxury', 'Vacation/Resort'] },
      { name: 'timeHorizon', label: 'Time Horizon', type: 'select', options: ['Next 3 months', 'Next 6 months', 'Next 12 months', 'Next 2 years'] },
      { name: 'currentTrends', label: 'Current Trends', type: 'textarea', placeholder: 'Warm minimalism, biophilic design, curved furniture, earth tones' },
    ],
  },
  'competitor-analysis': {
    desc: 'Comparable-listing competitive analysis (pricing, staging gaps, differentiation, marketing).',
    fields: [
      { name: 'subjectProperty', label: 'Subject Property', type: 'textarea', placeholder: 'e.g., 4 bed/3 bath single family, 2400 sqft, $850k, recently staged contemporary' },
      { name: 'comparables', label: 'Comparable Listings', type: 'textarea', placeholder: 'Up to 5 comps: address, price, sqft, beds/baths, status, days on market, staging notes' },
      { name: 'market', label: 'Market', type: 'text', placeholder: 'Austin, TX suburban' },
      { name: 'priceRange', label: 'Price Range', type: 'select', options: ['Under $300k', '$300k-$500k', '$500k-$800k', '$800k-$1.2M', '$1.2M-$2M', '$2M+'] },
      { name: 'targetSale', label: 'Target Sale Window', type: 'select', options: ['<14 days', '14-30 days', '30-60 days', '60+ days'] },
      { name: 'goals', label: 'Goals / Constraints', type: 'textarea', placeholder: 'Avoid price cut, beat top staged comp on appeal, maximize photo engagement' },
    ],
  },
  'buyer-persona-targeting': {
    desc: 'Top buyer personas with persona-specific staging, photography, and marketing guidance.',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['Single Family', 'Condo', 'Townhouse', 'Penthouse', 'Loft', 'Cabin', 'Luxury Estate'] },
      { name: 'location', label: 'Location', type: 'text', placeholder: 'Neighborhood, city, state' },
      { name: 'priceRange', label: 'Price Range', type: 'select', options: ['Under $300k', '$300k-$500k', '$500k-$800k', '$800k-$1.2M', '$1.2M-$2M', '$2M+'] },
      { name: 'features', label: 'Key Features', type: 'textarea', placeholder: 'Top features (e.g., chef kitchen, primary suite, walkable, top-rated schools)' },
      { name: 'lifestyle', label: 'Lifestyle Hints', type: 'textarea', placeholder: 'Optional notes (e.g., walk score 92, near tech offices, family district)' },
      { name: 'currentMarketing', label: 'Current Marketing Channels', type: 'textarea', placeholder: 'MLS, Zillow, agent IG, brokerage email blast' },
    ],
  },
};

export default aiFormConfigs;
