module.exports = {
  caseType:'staging_design_deliverable', initialState:'requirements_captured',
  states:['requirements_captured','site_verified','alternatives_ready','quantity_review','budget_review','render_review','approved','exported'],
  createRoles:['designer','project_manager'],
  evidenceKinds:['site_measurement_digest','licensed_asset_record','design_manifest','quantity_takeoff','catalog_snapshot','budget_snapshot','render_manifest','export_manifest'],
  requiredSignals:['measurementUnit','roomWidth','roomLength','catalogVersion','assetLicenseStatus','policyVersion'],
  assessmentRoles:['designer','project_manager','qualified_designer'],
  auditRoles:['project_manager','qualified_designer'],
  connectorRoles:['project_manager','production'],
  professionalBoundary:'Outputs are planning artifacts, not code or constructability certification; qualified designers and contractors approve deliverables.',
  connectors:[
    {name:'cad_bim_gis',purpose:'dimensioned model references'},
    {name:'product_catalog',purpose:'versioned cost and product data'},
    {name:'render_worker',purpose:'render job manifests'},
    {name:'contractor',purpose:'qualified review receipts'},
    {name:'object_storage',purpose:'encrypted artifact pointers'},
    {name:'permitting',purpose:'jurisdiction source references'},
  ],
  transitions:[
    {from:'requirements_captured',action:'verify_site',to:'site_verified',roles:['designer'],requiresEvidence:true},
    {from:'site_verified',action:'record_alternatives',to:'alternatives_ready',roles:['designer'],requiresEvidence:true},
    {from:'alternatives_ready',action:'review_quantities',to:'quantity_review',roles:['designer'],requiresEvidence:true},
    {from:'quantity_review',action:'review_budget',to:'budget_review',roles:['project_manager'],requiresEvidence:true,dualControl:true},
    {from:'budget_review',action:'submit_render_review',to:'render_review',roles:['designer'],requiresEvidence:true},
    {from:'render_review',action:'approve',to:'approved',roles:['qualified_designer'],requiresEvidence:true,dualControl:true},
    {from:'approved',action:'export',to:'exported',roles:['production'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>({disposition:Number(x.roomWidth)>0&&Number(x.roomLength)>0&&x.assetLicenseStatus==='verified'?'eligible_for_dimension_review':'site_or_rights_hold',constructability:null,assumptions:{unit:x.measurementUnit,catalogVersion:x.catalogVersion}}),
};
